apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: rohitbakshi/camtest2